apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacexstarlink-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spacexstarlink
  template:
    metadata:
      labels:
        app: spacexstarlink
    spec:
      containers:
      - name: spacexstarlink
        image: spacexstarlinkcntreg.azurecr.io/spacexstarlink:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Password
            value: Pass#word1 
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: spacexstarlink-service
spec:
  type: LoadBalancer
  selector:
    app: spacexstarlink
  ports:
  - port: 80
    targetPort: 80